# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

## Arrays

In [2]:
# Define array
a = np.array([1,2,3])

# Some basic properties
print("Array a: ", a)
print("\nShape of array a: ", a.shape)
print("\nData type of array a: ", a.dtype)

Array a:  [1 2 3]

Shape of array a:  (3,)

Data type of array a:  int32


In [14]:
# Define matrix
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)

# Some basic properties
print("Matrix b: \n", b)
print("\nShape of matrix b: ", b.shape)
print("\nData type of matrix b: ", b.dtype)

Matrix b: 
 [[1 2 3]
 [4 5 6]]

Shape of matrix b:  (2, 3)

Data type of matrix b:  int64


In [15]:
# Multidim arrays - tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], dtype=np.float64)

# Some basic properties
print("Tensor c: \n", c)
print("\nShape of tensor c: ", c.shape)
print("\nData type of tensor c: ", c.dtype)

Tensor c: 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

Shape of tensor c:  (2, 2, 3)

Data type of tensor c:  float64


## Initialization functions

In [17]:
# All zeros
print("All zeros: \n", np.zeros((2,2)))

# All ones
print("\nAll ones: \n", np.ones((2,3,4)))

# All same value
print("\nAll same value: \n", np.full((2,2), 2))

# All random
# Setting a random seed is important for reproducibility of the code.
# It is good practice to use it in ML before moving to actual training as it makes debuging a lot easier.
np.random.seed(5)
print("\nAll random: \n", np.random.random((2,2)))

# Identity matrix
print("\nIdentity matrix: \n", np.eye(3))

All zeros: 
 [[0. 0.]
 [0. 0.]]

All ones: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

All same value: 
 [[2 2]
 [2 2]]

All random: 
 [[0.22199317 0.87073231]
 [0.20671916 0.91861091]]

Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array indexing

Indexing starts from 0. It is possible to use negative indexes (for example -1 for last element of array)

In [18]:
print("Array a: ", a)
print("First element of a: ", a[0])
print("Last element of a: ", a[2])
print("Last element of a: ", a[-1])

Array a:  [1 2 3]
First element of a:  1
Last element of a:  3
Last element of a:  3


Indexing in matrix and tensor is the same and we can index any column, row etc.

In [32]:
print("Tensor c: \n", c)
print("\nValue of c[0]: \n", c[0])
print("\nValue of c[-2]: \n", c[-2])
print("\nValue of c[0][1]: ", c[0][1])
print("Value of c[0][0][0]: ", c[0][0][0])
print("Value of c[0, 0, 0]: ", c[0, 0, 0])
print("\nValue of c[0, :, 0:2]: \n", c[0, :, 0:2])

Tensor c: 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

Value of c[0]: 
 [[1. 2. 3.]
 [4. 5. 6.]]

Value of c[-2]: 
 [[1. 2. 3.]
 [4. 5. 6.]]

Value of c[0][1]:  [4. 5. 6.]
Value of c[0][0][0]:  1.0
Value of c[0, 0, 0]:  1.0

Value of c[0, :, 0:2]: 
 [[1. 2.]
 [4. 5.]]


## Basic operations

In [33]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print("Matrix x: \n", x)
print("\nMatrix y: \n", y)

Matrix x: 
 [[1. 2.]
 [3. 4.]]

Matrix y: 
 [[5. 6.]
 [7. 8.]]


In [35]:
print("Addition:\n", x + y)
print("Subtraction:\n", y - x)
print("Elementwise multiplication:\n", x * y)
print("Multiplication:\n", np.matmul(x, y))
print("Divison:\n", x / y)
print("Square root:\n", np.sqrt(x))
print("Exp:\n", np.exp(x))
print("Dot product:\n", np.dot(x[1], y[0]))
print("Transpose:\n", x.T)
print("Inverse:\n", np.linalg.inv(x))

Addition:
 [[ 6.  8.]
 [10. 12.]]
Substraction:
 [[4. 4.]
 [4. 4.]]
Elementwise multiplication:
 [[ 5. 12.]
 [21. 32.]]
Multiplication:
 [[19. 22.]
 [43. 50.]]
Divison:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Square root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
Dot product:
 39.0
Transpose:
 [[1. 3.]
 [2. 4.]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Broadcasting

Broadcasting is one of the most important numpy features. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 

In [36]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
print("a * b, a as vector, b as vector:", a * b)

b = np.array([2])
print("a * b, a as vector, b as scalar:", a * b)

a * b, a as vector, b as vector: [2. 4. 6.]
a * b, a as vector, b as scalar: [2. 4. 6.]


In [39]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([2,4,6])

print("Matrix a:\n", a)
print("Vector b:", b)
print("a + b, a as matrix, b as vector:\n", a + b)
print("a * b, a as matrix, b as vector:\n", a * b)
print("Dot product of a and b:\n", np.dot(a, b))

Matrix a:
 [[1 2 3]
 [4 5 6]]
Vector b: [2 4 6]
a + b, a as matrix, b as vector:
 [[ 3  6  9]
 [ 6  9 12]]
a * b, a as matrix, b as vector:
 [[ 2  8 18]
 [ 8 20 36]]
Dot product of a and b:
 [28 64]


## Important ML functions:
### Sigmoid function:

\begin{equation*}
S(x) = \frac{1}{1 + e^{-x}}
\end{equation*}

You can find more at *https://en.wikipedia.org/wiki/Sigmoid_function*

In [ ]:
def sigmoid(x):
    # [TODO] Implement sigmoid function
    return 0

In [ ]:
print("Sigmoid of \"0\":", sigmoid(0))
print("Expected value: 0.5")
testArray = np.array([1,5])
print("Sigmoid of [1,5]:", sigmoid(testArray))
print("Expected value: [0.73105858 0.99330715]")

### Ploting Sigmoid

In [ ]:
x = np.arange(-10., 10., 0.2)
y = sigmoid(x)
plt.plot(x,y)
plt.show()